on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-typescript-workflow.yml
    - packages/plugin-compat/sources/patches/typescript.patch.ts
    - scripts/e2e-setup-ci.sh

name: 'TypeScript PnP patch'
jobs:
  chore:
    name: 'Validating individual TypeScript versions'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tsversion: [3.5, 3.6, 3.7, 3.8, 3.9, 4.0, beta]
    steps:
    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli
    - name: 'Running the integration test on ${{ matrix.tsversion }}'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add typescript@${{ matrix.tsversion }}

        yarn add ts-pnp left-pad @types/left-pad

        echo '{"compilerOptions": {"baseUrl": ".", "strict": true, "esModuleInterop": true}}' > tsconfig.json

        echo "const foo: number = 42;" | tee file.ts
        yarn tsc --noEmit

        echo "const foo: number = 'error';" | tee file.ts
        ! yarn tsc --noEmit

        echo "import {resolveModuleName} from 'ts-pnp'; const foo: (...args: any[]) => any = resolveModuleName;" | tee file.ts
        yarn tsc --noEmit

        echo "import {resolveModuleName} from 'ts-pnp'; const foo: number = resolveModuleName;" | tee file.ts
        ! yarn tsc --noEmit

        echo "import leftPad from 'left-pad'; const foo: string = leftPad('hello', 42, ' ');" | tee file.ts
        yarn tsc --noEmit

        echo "import leftPad from 'left-pad'; const foo: number = leftPad('hello', 42, ' ');" | tee file.ts
        ! yarn tsc --noEmit

        echo "process.exit(42);" | tee file.ts
        ! yarn tsc --noEmit

        yarn add @types/node

        echo "process.exit(42);" | tee file.ts
        yarn tsc --noEmit
